---
# Elasticsearch Ansible Tasks

# Information outputs
- name: Install following ElasticSearch version
  ansible.builtin.debug:
    var: elasticsearch_version

- name: Plugin vars info output
  ansible.builtin.debug:
    var: elasticsearch_plugins
- ansible.builtin.debug:
    var: elasticsearch_aws_s3
- ansible.builtin.debug:
    var: elasticsearch_aws_discovery

- name: Heap size info
  ansible.builtin.debug:
    var: elasticsearch_heap_size

# Preparations and dependency installs
- name: Configuring timezone
  ansible.builtin.shell:
    cmd: echo {{ elasticsearch_timezone }} > /etc/timezone; dpkg-reconfigure --frontend noninteractive tzdata
  when: elasticsearch_timezone is defined

- name: Add specified repos and update apt index
  ansible.builtin.apt_repository:
    repo: '{{ item }}'
    state: present
    update_cache: yes
  with_items: '{{ elasticsearch_apt_repos }}'

- name: Install Java package
  ansible.builtin.apt:
    pkg: '{{ elasticsearch_apt_java_package }}'
    state: present
  when: elasticsearch_install_java

- name: Install other packages specified as dependencies
  ansible.builtin.apt:
    pkg: '{{ elasticsearch_apt_dependencies }}'
    state: present

- name: Creating elasticsearch system group
  ansible.builtin.group:
    name: '{{ elasticsearch_group }}'

- name: Creating elasticsearch system user
  ansible.builtin.user:
    name: '{{ elasticsearch_user }}'
    group: '{{ elasticsearch_group }}'
    createhome: no

- name: Check whether we have aleady installed the same version
  ansible.builtin.shell:
    cmd: if [ -e /usr/share/elasticsearch/lib/elasticsearch-{{ elasticsearch_version }}.jar ]; then echo yes; else echo no; fi;
  register: version_exists
  check_mode: no

- ansible.builtin.set_fact:
    elasticsearch_download_url: 'https://download.elasticsearch.org/elasticsearch/elasticsearch'
  when:
    - elasticsearch_download_url is undefined
    - elasticsearch_version is version_compare('5.0', '<')

- ansible.builtin.set_fact:
    elasticsearch_download_url: 'https://artifacts.elastic.co/downloads/elasticsearch'
  when:
    - elasticsearch_download_url is undefined
    - elasticsearch_version is version_compare('5.0', '>=')

- name: Download Elasticsearch deb if needed (below version 7.x)
  ansible.builtin.get_url:
    url: '{{ elasticsearch_download_url }}/elasticsearch-{{ elasticsearch_version }}.deb'
    dest: /tmp/elasticsearch-{{ elasticsearch_version }}.deb
    mode: 0440
  when:
    - elasticsearch_version is version_compare('7.0', '<')
    - version_exists.stdout == 'no'

- name: Download Elasticsearch deb if needed
  ansible.builtin.get_url:
    url: '{{ elasticsearch_download_url }}/elasticsearch-{{ elasticsearch_version }}-amd64.deb'
    dest: /tmp/elasticsearch-{{ elasticsearch_version }}.deb
    mode: 0440
  when:
    - elasticsearch_version is version_compare('7.0', '>=')
    - version_exists.stdout == 'no'

- name: Uninstalling previous version if applicable
  ansible.builtin.shell:
    cmd: dpkg --remove elasticsearch
  when: version_exists.stdout == 'no'

- ansible.builtin.file:
    path: /usr/share/elasticsearch
    state: absent
  when: version_exists.stdout == 'no'

- name: Install Elasticsearch deb
  ansible.builtin.shell:
    cmd: dpkg -i -E --force-confnew /tmp/elasticsearch-{{ elasticsearch_version }}.deb
  when: version_exists.stdout == 'no'

- name: Ensure correct permissions
  ansible.builtin.file:
    path: /usr/share/elasticsearch
    state: directory
    owner: '{{ elasticsearch_user }}'
    group: '{{ elasticsearch_group }}'
    recurse: yes

- name: Creating elasticsearch directories
  ansible.builtin.file:
    path: '{{ elasticsearch_log_dir }}'
    state: directory
    owner: '{{ elasticsearch_user }}'
    group: '{{ elasticsearch_group }}'
    recurse: yes
  when: elasticsearch_log_dir is defined

- ansible.builtin.file:
    path: '{{ elasticsearch_data_dir }}'
    state: directory
    owner: '{{ elasticsearch_user }}'
    group: '{{ elasticsearch_group }}'
    recurse: yes
  when: elasticsearch_data_dir is defined

- ansible.builtin.file:
    path: '{{ elasticsearch_work_dir }}'
    state: directory
    owner: '{{ elasticsearch_user }}'
    group: '{{ elasticsearch_group }}'
    recurse: yes
  when: elasticsearch_work_dir is defined

- name: Configuring open file limits
  ansible.builtin.lineinfile:
    dest: /etc/security/limits.conf
    regexp: '^{{ elasticsearch_user }}     -    nofile    {{ elasticsearch_max_open_files }}'
    insertafter: EOF
    line: '{{ elasticsearch_user }}     -    nofile    {{ elasticsearch_max_open_files }}'
  when: elasticsearch_max_open_files is defined
  notify: Restart Elasticsearch

- ansible.builtin.lineinfile:
    dest: /etc/security/limits.conf
    regexp: '^{{ elasticsearch_user }}     -    memlock   {{ elasticsearch_max_locked_memory }}'
    insertafter: EOF
    line: '{{ elasticsearch_user }}     -    memlock   {{ elasticsearch_max_locked_memory }}'
  when: elasticsearch_max_locked_memory is defined
  notify: Restart Elasticsearch

- ansible.builtin.lineinfile:
    dest: /etc/pam.d/su
    regexp: '^session    required   pam_limits.so'
    insertafter: EOF
    line: 'session    required   pam_limits.so'
  notify: Restart Elasticsearch

- ansible.builtin.lineinfile:
    dest: /etc/pam.d/common-session
    regexp: '^session    required   pam_limits.so'
    insertafter: EOF
    line: 'session    required   pam_limits.so'
  notify: Restart Elasticsearch

- ansible.builtin.lineinfile:
    dest: /etc/pam.d/common-session-noninteractive
    regexp: '^session    required   pam_limits.so'
    insertafter: EOF
    line: 'session    required   pam_limits.so'
  notify: Restart Elasticsearch

- ansible.builtin.lineinfile:
    dest: /etc/pam.d/sudo
    regexp: '^session    required   pam_limits.so'
    insertafter: EOF
    line: 'session    required   pam_limits.so'
  notify: Restart Elasticsearch

# Install custom JARs
- include_tasks: custom-jars.yml
  when: elasticsearch_custom_jars is defined

# Configure Elasticsearch Node, depending on version
- include_tasks: configure_2x.yml
  when: elasticsearch_version is version_compare('5.0', '<')

- include_tasks: configure_5x.yml
  when:
    - elasticsearch_version is version_compare('5.0', '>=')
    - elasticsearch_version is version_compare('6.0', '<')

- include_tasks: configure_6x.yml
  when: elasticsearch_version is version_compare('6.0', '>=')

# Install Plugins with ES 2.0 - 2.4 (ES version 5.0 follows 2.4)
- include_tasks: plugins_2x.yml
  when:
    - elasticsearch_version is version_compare('2.0', '>=')
    - elasticsearch_version is version_compare('5.0', '<')

# Install Plugins with ES 5.x
- include_tasks: plugins_5x.yml
  when:
    - elasticsearch_version is version_compare('5.0', '>=')
    - elasticsearch_version is version_compare('6.0', '<')

# Install Plugins with ES 6.x
- include_tasks: plugins_6x.yml
  when:
    - elasticsearch_version is version_compare('6.0', '>=')

# Register Elasticsearch service to start on boot
- name: Ensure Elasticsearch is started on boot
  ansible.builtin.service:
    name: elasticsearch
    enabled: '{{ elasticsearch_service_startonboot }}'
    state: '{{ elasticsearch_service_state }}'

# Copy ES maintainance scripts to machine
- name: Copy reroute script to machine
  ansible.builtin.copy:
    src: unassigned-reroute.sh
    dest: '{{ elasticsearch_scripts_dir }}/unassigned-reroute.sh'
    mode: 'u=rwx'
  when: elasticsearch_scripts_dir is defined
