---
# Install Elasticsearch Plugins (works only with the plugin script/system from ES => 2.0.0)
# You will need to define an array called 'elasticsearch_plugins' in your playbook or inventory, such that:
#
# elasticsearch_plugins:
#  - { name: '<plugin name>', url: '<[optional] plugin url>' }
#  - ...
# where if you were to install the plugin via bin/plugin, you would type:
#
# bin/plugin install <plugin name>
# or
# bin/plugin install <plugin url>

# Cleanup installed plugins first
- name: (ES 2.x mode) Determining which plugins are installed
  ansible.builtin.shell:
    cmd: '{{ elasticsearch_home_dir }}/bin/plugin list | grep -E " - [[:alnum:]_-]+"'
  register: elasticsearch_installed_plugins
  changed_when: false

- name: (ES 2.x mode) Removing Plugins if they exist
  ansible.builtin.shell:
    cmd: bin/plugin remove {{ item }}
    chdir: '{{ elasticsearch_home_dir }}'
  when: "'No plugin' not in item"
  with_items: '{{ elasticsearch_installed_plugins.stdout | from_yaml }}'

# Loop through elasticsearch_plugins and install them
- name: (ES 2.x mode) Installing Plugins by Name (use for official plugins within the elasticsearch repo)
  ansible.builtin.shell:
    cmd: bin/plugin install {{ item.name }}
    chdir: '{{ elasticsearch_home_dir }}'
  when: item.url is undefined
  with_items: '{{ elasticsearch_plugins }}'

- name: (ES 2.x mode) Installing Plugins by URL (use for 3rd party plugins)
  ansible.builtin.shell:
    cmd: bin/plugin install {{ item.url }}
    chdir: '{{ elasticsearch_home_dir }}'
  when: item.url is defined
  with_items: '{{ elasticsearch_plugins }}'
  ignore_errors: true
  # have to ignore errors here as plugin scripts returns non zero when checksums are missing

# Install AWS Plugin (see https://github.com/elasticsearch/elasticsearch-cloud-aws)
- name: (ES 2.x mode) Installing AWS Plugin
  ansible.builtin.shell:
    cmd: bin/plugin install cloud-aws
    chdir: '{{ elasticsearch_home_dir }}'
  when: elasticsearch_aws_s3 or elasticsearch_aws_discovery

# Fix permissions
- name: Fix plugin file permission
  ansible.builtin.file:
    path: "{{ elasticsearch_plugin_dir }}"
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    recurse: yes

# List installed plugins
- name: Get installed plugins
  ansible.builtin.shell:
    cmd: '{{ elasticsearch_home_dir }}/bin/plugin list'
  register: elasticsearch_plugin_list
  changed_when: false

- name: Output installed ES 2.x plugins
  ansible.builtin.debug:
    msg: "{{ elasticsearch_plugin_list.stdout }}"
