---

name: Ansible-Test
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        test_play: ['test-2.yml', 'test-5.yml', 'test-6.yml']
    env:
      ANSIBLE_FORCE_COLOR: true
    steps:

      - name: Checkout code from Github
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install latest Ansible through pip
        run: pip install ansible

      - name: Output python and ansible versions
        run: |
          python --version
          ansible --version

      - name: Create ansible.cfg with correct roles_path
        run: printf '[defaults]\nroles_path=../' > ansible.cfg

      - name: Basic Ansible role syntax check
        run: ansible-playbook -i tests/inventory --syntax-check tests/${{ matrix.test_play }}

      - name: Real Ansible run
        run: ansible-playbook -i tests/inventory tests/${{ matrix.test_play }}

      - name: Second run to check for indempotence (allowing 5 changes)
        run: "ansible-playbook -i tests/inventory tests/${{ matrix.test_play }} | grep -q 'changed=5.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
        if: ${{ matrix.test_play != 'test-2.yml' }}

      - name: test-2.yml Second run to check for indempotence (allowing 6 changes)
        run: "ansible-playbook -i tests/inventory tests/${{ matrix.test_play }}" # | grep -q 'changed=6.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
        if: ${{ matrix.test_play == 'test-2.yml' }}

      - name: Test ES with curl
        run: curl http://localhost:9200

      - name: Setup serverspec (install gem)
        run: sudo gem install serverspec

      - name: Run serverspec (as root to test everything)
        run: sudo rake spec PLAY=${{ matrix.test_play }}

